config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'

  get 'new_crawls' => 'crawls#new', :as => "new_crawl"
  resources :crawls
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crawl.rb
class Crawl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
	

	def index
		@crawls = Crawl.all
	end

	def show
		@crawl = Crawl.find(params[:id])
	end

	def new
		@crawl = Crawl.new
		puts %x( python ~/projects/Spider/lib/fuzzer/src/spider.py discover http://localhost:3001 )
	end

	def edit
		@crawl = Crawl.find(params[:id])
	end
	
	def create
		@crawl = Crawl.new( crawl_params )
		
		if @crawl.save
			redirect_to @crawl
		else
			render 'new'
		end
	end

	def update
		@crawl = Crawl.find(params[:id])

		if @crawl.update(crawl_params)
			redirect_to @crawl
		else
			render 'edit'
		end
	end

	def destroy
		@crawl = Crawl.find(params[:id])
		@crawl.destroy

		redirect_to crawls_path
	end

	private
		def crawl_params
			params.require(:crawl).permit(:app_url)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawls_helper.rb
module CrawlsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/crawls/new.html.erb
<h1>New Crawl</h1>

<%= form_for @crawl do |f| %>
 
  <% if @crawl.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@crawl.errors.count, "error") %> prohibited
        this crawl from being saved:
      </h2>
      <ul>
        <% @crawl.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :app_url %><br>
    <%= f.text_field :app_url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spider</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the Spider</h1>

<%= link_to 'Discover', new_crawl_path %><br />
<%= link_to 'Test' %>